<a href="https://colab.research.google.com/github/yahyaahmedkhann/pytorch-fundamentals/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [79]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [80]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

## Creating Tensors

Pytorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [81]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [82]:
scalar.ndim

0

In [83]:
# Get tensor back as Python int
scalar.item()

7

In [84]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [85]:
vector.ndim

1

In [86]:
vector.shape

torch.Size([2])

In [87]:
# MATRIX
MATRIX = torch.tensor([[5,6],
                      [7,8]])
MATRIX

tensor([[5, 6],
        [7, 8]])

In [88]:
MATRIX.ndim

2

In [89]:
MATRIX.shape

torch.Size([2, 2])

In [90]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [91]:
TENSOR.ndim

3

In [92]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> Look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [93]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0685, 0.1358, 0.5702, 0.3876],
        [0.1294, 0.4134, 0.1765, 0.9572],
        [0.7871, 0.4083, 0.9044, 0.1650]])

In [94]:
random_tensor.ndim

2

In [95]:
# Create a random tensor with similar shape to a image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and Ones

In [96]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [97]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [98]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [99]:
ones.dtype

torch.float32

# Create a range of tensors and tensors-like

In [100]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
# Creating a tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor DataTypes

**Note:** Tensor datatypes is one of the 3 big errors with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. TEnsors not on the right device

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [102]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [103]:
float_32_tensor.dtype

torch.float32

In [104]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [105]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [106]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [107]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

## Getting Information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor , can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [108]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5727, 0.1612, 0.4010, 0.4880],
        [0.4810, 0.0537, 0.7653, 0.0824],
        [0.3716, 0.0426, 0.5414, 0.5181]])

In [109]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor is on: {some_tensor.device}")

tensor([[0.5727, 0.1612, 0.4010, 0.4880],
        [0.4810, 0.0537, 0.7653, 0.0824],
        [0.3716, 0.0426, 0.5414, 0.5181]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor Operations include:

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [110]:
# Create a tensor (add 10 to it)
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [111]:
# Multiply a tensor by 10
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [112]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [113]:
# Pytorch in built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [114]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning.

1. Element wise Multiplication
2. Matrix Multiplication (Dot Product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:

* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**

* `(2,3) @ (3,2)` -> (2,2)
* `(3,2) @ (2,3)` -> (3,3)

In [115]:
# Example for inner dimensions that won't work
#torch.matmul(torch.rand(3,2), torch.rand(3,2))


#RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [116]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [117]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [118]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.79 ms, sys: 44 µs, total: 1.83 ms
Wall time: 3.22 ms


In [119]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 76 µs, sys: 0 ns, total: 76 µs
Wall time: 80.3 µs


tensor(14)

### One of the most common errors in deep learning is shape errors



In [120]:
# Shapes for matrix multiplication
tensor_A =torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B = torch.tensor([[7,11],
                        [8,12],
                        [9,13]])

# tensor.mm(tensor_A, tensor_B) # tensor.mm is same as tensor.matmul
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [121]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [122]:
# To fix tensor shape issues, we use transpose matrix
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [11, 12, 13]]),
 torch.Size([2, 3]))

In [123]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 29,  32,  35],
        [ 65,  72,  79],
        [101, 112, 123]])

In [124]:
# The matrix multiplication operations works when we transpose one of the matrix
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A}, tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"Output\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\n Output shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = tensor([[1, 2],
        [3, 4],
        [5, 6]]), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output

tensor([[ 29,  32,  35],
        [ 65,  72,  79],
        [101, 112, 123]])

 Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [125]:
# Create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [126]:
# Find the min
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [127]:
# Find the max
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [128]:
# Find the sum
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

In [129]:
# Find the mean - note: torch.mean requires a tensor of float32 datatype to work
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

(tensor(45.), tensor(45.))

### Finding the positional min and max


In [130]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [131]:
# Find the position where the minimum value occurs and returns it's index value
x.argmin()

tensor(0)

In [132]:
# Find the position where the maximum value occurs and returns it's index value
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of eachother (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permutted (swapped) in a certain way

In [133]:
# Create a tensor
import torch
y = torch.arange(1.,10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [134]:
# Add an extra dimension
y_reshaped = y.reshape(1,9)
y_reshaped, y_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [135]:
# Change the view
z = y.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [136]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 6
z, y

(tensor([[6., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([6., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [137]:
# Stack tensors on top of each other
y_stacked = torch.stack([y,y,y,y], dim=0)
y_stacked

tensor([[6., 2., 3., 4., 5., 6., 7., 8., 9.],
        [6., 2., 3., 4., 5., 6., 7., 8., 9.],
        [6., 2., 3., 4., 5., 6., 7., 8., 9.],
        [6., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [142]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {y_reshaped}")
print(f"Previous shape: {y_reshaped.shape}")

# remove extra dimensions from y_reshaped
y_squeezed = y_reshaped.squeeze()
print(f"\nNew Tensor: {y_squeezed}")
print(f"New shape: {y_squeezed.shape}")

Previous tensor: tensor([[6., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New Tensor: tensor([6., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [143]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous Tensor: {y_squeezed}")
print(f"Previous shape: {y_squeezed.shape}")

# Add an extra dimension with unsqueeze
y_unsqueezed = y_squeezed.unsqueeze(dim=0)
print(f"\n New Tensor: {y_unsqueezed}")
print(f"New shape: {y_unsqueezed.shape}")

Previous Tensor: tensor([6., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

 New Tensor: tensor([[6., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [144]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
y_original = torch.rand(size=(224,224,3)) # (height, width, color_channels)

# permute the original tensor to rearrage the axis (or dim) order
y_permuted = y_original.permute(2, 0, 1) # index changes

print(f"Previous shape: {y_original.shape}")
print(f"New shape: {y_permuted.shape}") # color_channels, height, width

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [145]:
y_original

tensor([[[0.5180, 0.6203, 0.7484],
         [0.3801, 0.1321, 0.9083],
         [0.4807, 0.4436, 0.5228],
         ...,
         [0.6492, 0.2616, 0.2359],
         [0.3957, 0.6020, 0.4671],
         [0.6692, 0.3924, 0.1416]],

        [[0.2290, 0.3502, 0.2127],
         [0.7230, 0.7039, 0.3496],
         [0.6263, 0.6184, 0.9510],
         ...,
         [0.5764, 0.2760, 0.3065],
         [0.7514, 0.3253, 0.0689],
         [0.8660, 0.5529, 0.7508]],

        [[0.4764, 0.2953, 0.8541],
         [0.5992, 0.4192, 0.9078],
         [0.3975, 0.1043, 0.2666],
         ...,
         [0.3723, 0.3363, 0.4392],
         [0.2682, 0.0767, 0.5949],
         [0.1452, 0.4109, 0.1769]],

        ...,

        [[0.7288, 0.3097, 0.2254],
         [0.1060, 0.4360, 0.1646],
         [0.0239, 0.3953, 0.7069],
         ...,
         [0.9610, 0.0499, 0.1678],
         [0.4146, 0.2388, 0.7595],
         [0.4558, 0.7645, 0.4376]],

        [[0.1786, 0.7548, 0.0802],
         [0.1721, 0.2573, 0.4595],
         [0.

In [146]:
y_original [0,0,0] = 62732
y_original[0,0,0], y_permuted[0,0,0]

(tensor(62732.), tensor(62732.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [148]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [149]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [150]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [152]:
# Let's index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [153]:
# Also we can use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [154]:
# Get all values of 0th and 1st dimensons but only index 1 of  2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [155]:
# Get all the values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [156]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

## PyTorch Tensors & NumPy

NumPy is a popular scientific PYthon numerical computing library.

and because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [158]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning: You can change the datatype of a tensor because tensor default dtype is float32 by .type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [160]:
# If we change the value of an arraym what will this do to a "tensor"
array = array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [162]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [164]:
# Change the tensor, what happens to numpy tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take random out of random)

To reduce the randomness in neural networks and PyTorch comes the concept of a `random seed`

For research: https://pytorch.org/docs/stable/notes/randomness.html


In [165]:
# Using random seed
import torch

# Create two random tensors
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [168]:
# Create two random tensors
random_tensor_C = torch.rand(3,4)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.5315, 0.1587, 0.6542, 0.3278],
        [0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666]])
tensor([[0.9811, 0.0874, 0.0041, 0.1088],
        [0.1637, 0.7025, 0.6790, 0.9155],
        [0.2418, 0.1591, 0.7653, 0.2979]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


# Check for GPU access with PyTorch

Using a GPU results in faster computations.

1. Google colab or Google colab pro
2. To buy a gpu or an investment
3. Microsoft Azure, AWS etc

In [169]:
import torch
torch.cuda.is_available()

False

In [170]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [171]:
# Count number of devices
torch.cuda.device_count()

0

In [172]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [173]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [174]:
# Move tensor to CPU from GPU (in our case, we are on free version, so there is no cuda)

# PyTorch has a device issue as well where we can't simply convert GPU to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu


array([1, 2, 3])